apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello-world
    ports:
    - containerPort: 3000
    resources:
      requests:
        cpu: "100m"
        memory: "500Mi"
        ephemeral-storage: "1Gi"
      limits:
        memory: "500Mi"
        ephemeral-storage: "2Gi"
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
