apiVersion: batch/v1
kind: Job
metadata:
  name: random-hash
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - "echo $RANDOM | base64 | head -c 20"
        image: alpine
        name: random-hash
      restartPolicy: Never
