apiVersion: batch/v1
kind: Job
metadata:
  name: random-hash
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - image: alpine
        name: random-hash
        command: ["/bin/sh", "-c", "echo $RANDOM | base64 | head -c 20"] 
      restartPolicy: Never
