apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: web-app
  namespace: y72
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: web-app
  type: ClusterIP
status:
  loadBalancer: {}
