apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - image: busybox:1.36.1
    name: app
    command:
    - /bin/sh
    - -c
    - 'while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep 5; done;'
    volumeMounts:
    - mountPath: /var/logs
      name: log-volume
  - image: busybox:1.36.1
    name: transformer
    command:
    - /bin/sh
    - -c
    - 'sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;'
    volumeMounts:
    - mountPath: /var/logs
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
