apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello-world
    ports:
    - containerPort: {{ .Values.container_port }}
