apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello
    ports:
    - name: nodejs-port
      containerPort: 3000
    readinessProbe:
      httpGet:
        port: nodejs-port
        path: /
      initialDelaySeconds: 2 
    livenessProbe:
      httpGet:
        port: nodejs-port
        path: /
      initialDelaySeconds: 5 
      periodSeconds: 8
