apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world
  name: web-app-service
spec:
  ports:
  - port: {{ .Values.service_port }}
    protocol: TCP
    targetPort: {{ .Values.container_port }}
  selector:
    name: hello-world
  type: ClusterIP
