apiVersion: v1
kind: Pod
metadata:
  name: service-list
  namespace: t23
spec:
  containers:
  - image: alpine/curl:3.14
    name: service-list
    command:
    - /bin/sh
    - -c
    - 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);while true; do curl -s -k -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/default/services;sleep 10; done;'
  serviceAccountName: api-call
