apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  securityContext:
    fsGroup: 2000
  containers:
  - image: busybox:1.28
    name: busybox-security-context
    command: 
    - /bin/sh
    - -c
    - sleep 1h
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /data/test
      name: output-volume
  volumes:
  - name: output-volume
    emptyDir: {}
