apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - image: nginx:1.23.4-alpine
    name: backend
    volumeMounts:
    - mountPath: /etc/config
      name: configpv
  volumes:
  - name: configpv
    configMap:
      name: app-config
